### ISSUE TITLE
Move to PEP420 implicit namespaces

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/meta#261] opened 2024-07-29 14:52 UTC
There are no longer any Python versions we support which do not allow for implicit namespace packages.  Ideally, we would just zap `src/zope/__init__.py` (and other namespaces) wholesale, remove `setuptools` from our `install_requires`, and push out new releases for all the dang packages.

I'm uncertain how this will work out for downstreams which might pin older versions of some of our projects, while not pinning all of them.

**Comment by mauritsvanrees** [comment] 2024-07-30 13:34
Duplicate of issue #194 which has more info, so I close this one.

Summary from how I remember it:

* Within one namespace (say `zope`) you can pip install native and non-native namespace packages together.
* But if you use an editable install (because you are developing a package), then for those editable packages you must use either native or non-native namespaces, not a combination.
* So it seems best to migrate all packages around the same time.  Otherwise when someone wants to fix a bug in a not-yet-migrated package, they cannot even develop it, because they would first need to migrate it to native namespaces.
* Not sure if Buildout handles this well.

From a Plone standpoint it should not be a problem if all `zope.*` packages would suddenly be native.  But this is not the case for the `Products` namespace, as there are both Plone and Zope (and CMF) packages that use this namespace.  As Plone release manager I hope that Zope can wait until we start working on Plone 7 (2025 or 2026) before migrating the Products namespace.

**Closed** 2024-07-30 13:34 UTC

**Comment by icemac** [comment] 2024-07-31 06:33
> * Within one namespace (say `zope`) you can pip install native and non-native namespace packages together.

Sadly this will not work – I have been bitten by this issue for some sphinxcontrib packages which were not yet ported to implicit namespace usage. Additionally the error message you get is totally missleading.
So the only way forward is to port all packages of one namespace at once.

**Comment by tseaver** [comment] 2024-07-31 14:14
@icemac The [PyPA docs on migrating namespace packages](https://github.com/pypa/sample-namespace-packages) say that it is unsupported, but may work with some caveats.  In particular, the [successful testing they have done](https://github.com/pypa/sample-namespace-packages/blob/master/table.md) relied on using `pip` with build isolation and build-backend APIs, which requires porting packages to use `pyproject.toml`.

**Comment by icemac** [comment] 2024-08-02 06:39
@tseaver Then `buildout` is probably our problem: It does not support develop installs for packages using `pyproject.toml` and I've seen the problems I described in a buildout environment.
