### ISSUE TITLE
Pin flake8 to prevent linting issues

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#18] opened 2020-05-12 23:58 UTC
There was a new `flake8` release yesterday, and since today we have loads of build failures because of `AttributeError: type object 'HTMLPlugin' has no attribute 'name'`.

`flake8-html` has not been maintained for the last 3 years, and I see no gain in using this plugin.
https://github.com/lordmauve/flake8-html

I propose to drop it from all repos.

At tomorrorw's/today's sprint I want to play around with some tools which
- finds all occurrences
- fix the tox.ini s
- create PRs for all affected repos at once (hoooo)

**Comment by jugmac00** [comment] 2020-05-13 00:35
There is a pr to fix the plugin... but who knows whether and when this will be merged.
https://github.com/lordmauve/flake8-html/pull/16

**Comment by dataflake** [comment] 2020-05-13 05:15
You can easily pin the flake8 version number in tox.ini to 3.7.9 to fix that.

**Comment by jugmac00** [comment] 2020-05-13 07:17
I do not see any reason to generate HTML output for linting errors, which should be fixed anyway before pushing to GitHub. And especially as this plugin is unmaintained - at least, currently it looks that way.

Maybe this is something we can talk about at the sprint opening meeting.

As you cannot take part, could you please give your reasons for keeping this plugin?

**Comment by dataflake** [comment] 2020-05-13 07:26
The plugin is not the issue. Pinning flake8 to version 3.7.9 solves the problem. Look at https://github.com/zopefoundation/Products.ExternalMethod/blob/8654970bdf0b05edd5f13d772046731b9324bd16/tox.ini#L41 and below for the end result for Products.ExternalMethods. `tox` runs through without error and the HTML plugin generates a nice-looking report I can open in a browser.

**Comment by dataflake** [comment] 2020-05-13 07:33
P.S.: Whether flake8 or a plugin for flake8 is maintained or not is completely beside the point here. The issue is breaking linter runs in tox. A simple version pin fixes that. If that really bothers you you're obviously welcome to come up with a different solution, but I don't think that's a good use of sprint time when such a small change fixes the real issue.

**Comment by jugmac00** [comment] 2020-05-14 06:42
Looks like my gut feeling was completely wrong and there will be a bug fix release.

This would avoid both dropping flake8-html (which you don't want) and pinning flake8 which the other sprinters didn't like.

https://github.com/lordmauve/flake8-html/issues/17

**Comment by dataflake** [comment] 2020-05-14 07:48
That's totally fine with me. I just want to avoid dropping a helpful tool and plugin due to an issue that can be fixed so easily.

**Comment by icemac** [comment] 2020-05-15 06:27
https://pypi.org/project/flake8-html/0.4.1/ is now released. Closing this issue as we do not have pins for `flake8*` so it should be picked up automatically.

Maybe we should add flake8 and the plug-ins to constraints.txt in Zope so we have an easy way to get around issues like this in the future.
I created https://github.com/zopefoundation/Zope/issues/826 therefore.

**Closed by icemac** 2020-05-15 06:27 UTC

**Comment by jugmac00** [comment] 2020-05-15 06:34
The new flake8 version brought some new or updated linting restrictions with it, so we now have some more build failures.

If anybody is curious to try out the flake8-html plugin - the html gets rendered in `parts/lint/index.html`.
